services:
  postgres:
    image: postgres:17
    container_name: artspace-postgres
    environment:
      POSTGRES_PASSWORD: artspace123
      POSTGRES_MULTIPLE_DATABASES: authdb,artdb,commentdb,notificationdb,commissiondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: artspace-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build: ./AuthService
    restart: on-failure
    ports:
      - "5144:8080"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=authdb;Username=postgres;Password=artspace123
      - Jwt__Secret=artspace_super_secret_key_123456789_must_be_long
      - Jwt__Issuer=artspace
      - Jwt__Audience=artspace

  art-service:
    build: ./ArtService
    restart: on-failure
    ports:
      - "5280:8080"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=artdb;Username=postgres;Password=artspace123
      - Jwt__Secret=artspace_super_secret_key_123456789_must_be_long
      - Jwt__Issuer=artspace
      - Jwt__Audience=artspace

  comment-service:
    build: ./CommentService
    restart: on-failure
    ports:
      - "5285:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=commentdb;Username=postgres;Password=artspace123
      - RabbitMQ__HostName=rabbitmq
      - Jwt__Secret=artspace_super_secret_key_123456789_must_be_long
      - Jwt__Issuer=artspace
      - Jwt__Audience=artspace

  notification-service:
    build: ./NotificationService
    restart: on-failure
    ports:
      - "5012:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=notificationdb;Username=postgres;Password=artspace123
      - RabbitMQ__HostName=rabbitmq
      - Jwt__Secret=artspace_super_secret_key_123456789_must_be_long
      - Jwt__Issuer=artspace
      - Jwt__Audience=artspace

  commission-service:
    build: ./CommissionService
    restart: on-failure
    ports:
      - "5013:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=commissiondb;Username=postgres;Password=artspace123
      - RabbitMQ__HostName=rabbitmq
      - Jwt__Secret=artspace_super_secret_key_123456789_must_be_long
      - Jwt__Issuer=artspace
      - Jwt__Audience=artspace

  api-gateway:
    build: ./ApiGateway/ApiGateway
    restart: on-failure
    ports:
      - "5092:8080"
    depends_on:
      - auth-service
      - art-service
      - comment-service
      - notification-service
      - commission-service

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

volumes:
  postgres_data: